---
title: "Hello R"
output:
  html_document:
    df_print: paged
    code_folding: show
---

Starting learning R by loading some data and making some plots.

```{r}
# Libraries
library(ggplot2)
```

```{r}
# Read data
data <- read.csv('../data/heart.csv')

# Make the target variable a factor
data$target <- as.factor(data$target)

# Print first few rows
head(data)
```

```{r}
# Print the structure of the data
str(data)
```

```{r}
# Plot the distribution of the target variable
ggplot(data, aes(x=data$target, fill=data$target)) +
  geom_bar() +
  xlab("Patient has a heart disease?") +
  ylab("Count") +
  labs(title="Target variable distribution")
```


```{r}
# Plot the distribution of people age
ggplot(data, aes(x=data$age)) +
  geom_histogram(binwidth = 1) +
  xlab("Age") +
  ylab("Count") +
  labs(title="Age distribution")
```


```{r}
# Plot the distribution of people age divided by weather they have a disase or not
ggplot(data, aes(x=data$age, fill=data$target)) +
  geom_histogram(binwidth = 1) +
  xlab("Age") +
  ylab("Count") +
  labs(title="Age distribution")
```


```{r}
# Box plot of the age based on the target variable
ggplot(data, aes(x=data$target, y=data$age, fill=data$target)) +
  geom_boxplot() +
  xlab("Has a heart disease?") +
  ylab("Age") +
  labs(title="Box plot of the age based on the target variable")
```


```{r}
# Violin plot of the age based on the target variable
ggplot(data, aes(x=data$target, y=data$age, fill=data$target)) +
  geom_violin() +
  xlab("Has a heart disease?") +
  ylab("Age") +
  labs(title="Violin plot of the age based on the target variable")
```